#request resources + use analy environment


salloc --partition test --time 0-04:00 --mem 20gb
module load python
mamba activate analy
cd /n/home07/than157/desktop/done-large_projects/learn-better/evolm/finetune/llama-factory/
jupyter notebook --no-browser --ip=0.0.0.0 --port=8888

In [1]:
from datasets import load_dataset
import pandas as pd
import json
from tqdm import tqdm
import numpy as np

## load data

In [2]:
#dongboklee/MMLU-Pro-Llama-3.1-70B-Instruct-CoT
#test split (n=131k) --> our training set
#val split (n=840 --> 70 unique questions) --> our test set

#load training set
train_dataset = load_dataset(path="dongboklee/MMLU-Pro-Llama-3.1-70B-Instruct-CoT", split="test")

df = train_dataset.to_pandas()
print("# samples:", df.shape[0])
print("# of unique questions:", df['question'].nunique())

df.head()

# samples: 130811
# of unique questions: 10532

,question_id,question,options,answer,answer_index,category,src,cot_id,cot_content
0,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,0,1. Advertising regulatory bodies typically aim...
1,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,1,"First, typical advertising regulatory bodies a..."
2,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,2,1. Advertising regulatory bodies typically aim...
3,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,3,Typical advertising regulatory bodies aim to e...
4,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,4,"First, typical advertising regulatory bodies a..."

In [3]:
#load test set
test_dataset = load_dataset(path="dongboklee/MMLU-Pro-Llama-3.1-70B-Instruct-CoT", split="validation")
test_df = test_dataset.to_pandas()
print(test_df.shape)
print("# of unique questions:", test_df['question'].nunique())

test_df.head()

(840, 9)
# of unique questions: 67

,question_id,question,options,answer,answer_index,category,src,cot_id,cot_content
0,0,The symmetric group $S_n$ has $\n\factorial{n}...,"[0, 30, 3, 10, 12, 50, 2, 100, 20, 5]",A,0,math,cot_lib-abstract_algebra,0,"We are given a problem with two parts, but the..."
1,0,The symmetric group $S_n$ has $\n\factorial{n}...,"[0, 30, 3, 10, 12, 50, 2, 100, 20, 5]",A,0,math,cot_lib-abstract_algebra,1,"To find the characteristic of the ring 2Z, we ..."
2,0,The symmetric group $S_n$ has $\n\factorial{n}...,"[0, 30, 3, 10, 12, 50, 2, 100, 20, 5]",A,0,math,cot_lib-abstract_algebra,2,We are asked to find the characteristic of the...
3,0,The symmetric group $S_n$ has $\n\factorial{n}...,"[0, 30, 3, 10, 12, 50, 2, 100, 20, 5]",A,0,math,cot_lib-abstract_algebra,3,The symmetric group $S_n$ indeed has $n!$ elem...
4,0,The symmetric group $S_n$ has $\n\factorial{n}...,"[0, 30, 3, 10, 12, 50, 2, 100, 20, 5]",A,0,math,cot_lib-abstract_algebra,4,We're given a question about the characteristi...

In [4]:
#df = train df 
#test_df = test df

## process training data

##### check whether all answers in cot response are correct -- no!

In [5]:
def extract_from_answer_is(c):
    split = c.split("answer is")
    if len(split) > 1:
        answer = split[-1].strip()
        if ":" in answer:
            answer = answer.split(":")[-1].strip()
        answer = answer.rstrip(".,;!?")
        return answer
    else:
        return None

In [6]:
df['extracted_answer'] = df.apply(lambda row: extract_from_answer_is(row['cot_content']), axis=1)

# number of incorrect answers
print('# incorrect answers: ', (df['extracted_answer'] != df['answer']).sum() )

# incorrect answers:  699

In [7]:
#examine incorrect answers
rows_w_incorrect_answer = df[df['extracted_answer'] != df['answer']]

for idx, row in rows_w_incorrect_answer.iterrows():
    print('Question: ', row['question'])
    print('COT: ', row['cot_content'][-100:])
    print('TrueAnswer: ', row['answer'])
    print('Extracted Answer: ', row['extracted_answer'])
    print('-' * 40)

Question:  Assume the following model (from the preceding problem). Y = C + I + G C = 100 + 0.6Y I = 0.2Y - 50i M_D = 0.25Y - 30i M_s = 65 G = 100 whose equilibrium level was found to be 500. Suppose that full employment level of income is 600, so that the desired change is 100. If the money supply is held constant, what change in govern-ment spending will be required to close the deflationary gap?
COT:  f the 40 is multiplied by 1.525 (which is 1/ 0.65) this is 61. So the answer should be 61.5, or (F).
TrueAnswer:  F
Extracted Answer:  None
----------------------------------------
Question:  Suppose the demand curve for oPads is given by $p=\frac{500-x}{10}, What is the elasticity value of this demand function.
COT:  s given, we can see that the only option that matches our calculations for a specific x is:

I. -1.5
TrueAnswer:  I
Extracted Answer:  None
----------------------------------------
Question:  Tim is a salesman who earns a guaranteed salary of $4800/year plus 4% of all sales up to $12,000; 5% of sales from $12,000 to $20,000; 6% of sales over $20,000 in any month. Last month Tim's sales were $21,750. Compute his gross earnings for last month.
COT:  culate the options and see which one is close to the $1385.

However, the $1385 isn't an option, but
TrueAnswer:  B
Extracted Answer:  None
----------------------------------------
Question:  Costs for producing one widget: Materials:2 parts (a) $25.00 per part Expenses :$10.00 Labor :20 operations (a) $5.00 per operation Based on the above information, which is the only valid conclusion? (A) The selling price should be $160 per widget. (B) labor rates are excessive (C) output is labor intensive (D) material costs are low
COT:  n our analysis, the only valid conclusion is that the output is labor-intensive.

The answer is (F).
TrueAnswer:  F
Extracted Answer:  (F)
----------------------------------------
Question:  Two power line construction routes are being considered. Route A is 15 miles long and goes around a lake. Each mile will cost $6,000 to build and $2,000 a year to maintain. At the end of fifteen years, each mile will have a salvage value of $3,000. Route B is an underwater line that cuts 5 miles across the lake. Construction costs will be $31,000 per mile and annual maintenance costs, $400 per mile. The salvage value at the end of fifteen years will be $6,000 per mile. Assuming interest is 8% and taxes are 3% of the construction costs of each power line, compare the annual costs of Route A and Route B for the first year.
COT:  ized construction cost is $90,000 * 0.11679 (15 years @ 8% interest) = $10,511 + 3% of this amount (
TrueAnswer:  A
Extracted Answer:  None
----------------------------------------
Question:  _______ and _______ are both examples of _______ -based theories which are based on basic universal principles of right and wrong.
COT:  nd "Ethics of rights and justice".

However, another option has the correct pairing of Deontological
TrueAnswer:  G
Extracted Answer:  None
----------------------------------------
Question:  Ms. Fogg is planning an around-the-world trip on which she plans to spend $10,000. The utility from the trip is a function of how much she actually spends on it (Y), given by U(Y) = ln Y. If there is a 25 percent probability that Ms. Fogg will lose $1,000 of her cash on the trip, what is the trip’s expected utility?
COT:   9.095 is closer to 9.100 but since 9.100 is closer to 9.150 than 9.095 to 9.100, 9.100 is closer to
TrueAnswer:  G
Extracted Answer:  None
----------------------------------------
Question:  The returns on a stock are 2.45% at 2018, 5.42% at 2019, -13.83% at 2020. What is the compound annual rate (between -1 and 1) of return over the three years.
COT:  ut -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available
TrueAnswer:  E
Extracted Answer:  n't available, we look for the closest answer which is -0.023669 (option E) but then -0.02666 is closer to -0.02678 isn't available but -0.02666 is closer to -0.02678 isn't available but -0.02666 is closer to -0.02678 isn't available but -0.02666 is closer to -0.02678 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available but -0.02666 is closer to -0.02366 isn't available
----------------------------------------
Question:  Suppose there are 100 identical firms in a perfectly competitive industry. Each firm has a short-run total cost function of the form C(q) = \frac{1}{300}q^3 + 0.2q^2 + 4q + 10. Suppose market demand is given by Q = -200P + 8,000. What will be the short-run equilibrium price?
COT:  ty supplied.

However, we don't have a quantity supplied equation. Instead, we can use the fact that
TrueAnswer:  A
Extracted Answer:  None
----------------------------------------
Question:  A city has a tax budget totaling $2,455,335. The tax rate is comprised of 52$ per $100 for construction, 31$ per $100 for general health and welfare and $1.42 per $100 for education. What is the assessed valuation of the taxable property?
COT:  301.22 * 100) / 100
X = $1,196,301.22
X = ($1,196,301.22 * 100) / 100
X = $1,196,301.22
X = ($1,
TrueAnswer:  J
Extracted Answer:  None
----------------------------------------
Question:  The workers of "K. Industry" are paid a bonus if they produce more than 180 micro circuits in a 40-hour workweek. The premium paid is 50% of the hours saved. They are paid $2.40 an hour. If worker 'A' completes 150 circuits in a week, and worker 'B' completes 198 circuits, how much more than worker 'A' must worker 'B' be paid?
COT:  s worker 'A' and completed 198 circuits. Worker 'A' completed 150 circuits in 40 hours, so worker 'A
TrueAnswer:  A
Extracted Answer:  None
----------------------------------------
Question:  The workers of "K. Industry" are paid a bonus if they produce more than 180 micro circuits in a 40-hour workweek. The premium paid is 50% of the hours saved. They are paid $2.40 an hour. If worker 'A' completes 150 circuits in a week, and worker 'B' completes 198 circuits, how much more than worker 'A' must worker 'B' be paid?
COT:  this is not correct.

However, worker 'A' does not save any hours since worker 'A' does not complete
TrueAnswer:  A
Extracted Answer:  None
----------------------------------------
Question:  The workers of "K. Industry" are paid a bonus if they produce more than 180 micro circuits in a 40-hour workweek. The premium paid is 50% of the hours saved. They are paid $2.40 an hour. If worker 'A' completes 150 circuits in a week, and worker 'B' completes 198 circuits, how much more than worker 'A' must worker 'B' be paid?
COT:   a bonus since he produced less than 180 circuits.

Time saved = 40 hours * (198 - 180) / 150 = 5.28
TrueAnswer:  A
Extracted Answer:  None
----------------------------------------
Question:  Mr.Allynreceived a note for $1800 bearing interest at 6% for 90 days, dated March 31 and due June 29. On April 20, his bank discounted the note at 6%. What were the proceeds?
COT:  is an option that is closer to the $1814.72 which is not available, but the closest is the option F.
TrueAnswer:  F
Extracted Answer:  not in the options. The closest option is C. $1810.00, but we can see that the correct calculation is close to another option, which is F. $1805.68 and also G. $1795.68 but another option is closer, which is I. $1827 but there is an option that is closer to the $1814.72 which is not available, but the closest is the option F
----------------------------------------
Question:  Estimate the PE ratio for a firm that has the following characteristics:
Length of high growth = five years
Growth rate in first five years = 25%
Payout ratio in first five years = 20%
Growth rate after five years = 8%
Payout ratio after five years = 50%
Beta = 1.0
Risk-free rate = T-bond rate = 6%
Cost of equity = 6% + 1(5.5%) = 11.5%
Risk premium = 5.5%
What is the estimated PE ratio for this firm?
COT:  llowing formula:

PE = ((Payout ratio in high growth phase * (1 + Growth rate in high growth phase)^
TrueAnswer:  A
Extracted Answer:  None
----------------------------------------
Question:  What is the difference in cost between three consecutive one-year policies and a 3-year policy for $28,000 worth of coverage if the rate is $.23 per $100?
COT:  - $128.80 = $64.40. $193.20 - $128.80 = $64.40. $193.20 - $128.80 = $64.40, however, $193.20 - $128.
TrueAnswer:  I
Extracted Answer:  None
----------------------------------------
Question:  Mr. Ed Williams, owner of a newspaper delivery service, bought a new truck for his business on the installment plan. The pertinent information is given below: Price of truck $3,000 Additional equipment 240 Sales tax 5% Insurance $ 60 Cash deposit $ 500 Used car allowance $ 732 Assume a 5% finance charge, find the amount to be financed, and deter-mine the amount to be paid each month to pay off the truck in one year
COT:  late the monthly payment:
Monthly payment = $2,341.50 / 12 = $195.125

The closest answer is D. $195
TrueAnswer:  D
Extracted Answer:  D. $195
----------------------------------------
Question:  A single firm monopolizes the entire market for widgets and can produce at constant average and marginal costs of AC = MC = 10. Originally, the firm faces a market demand curve given by Q = 60 - P. Calculate the profit-maximizing price for the firm.
COT:

We know that the firm's profit-maximizing output level occurs where MR = MC. Since MC = 10, we can
TrueAnswer:  H
Extracted Answer:  indeed among the options.

Let's try to solve the problem using a different approach.

We know that the firm's profit-maximizing output level occurs where MR = MC. Since MC = 10, we can
----------------------------------------
Question:  Which of the following is typically not a result of recognizing the importance of ethnic groups by marketers?
COT:  idering the options and the question's wording, the best answer is actually A, D, or H.

Considering
TrueAnswer:  B
Extracted Answer:  actually A, D, or H.

Considering
----------------------------------------
Question:  For a one-period binomial model for the price of a stock, you are given: (i) The period is one year. (ii) The stock pays no dividends. (iii) u =1.433, where u is one plus the rate of capital gain on the stock if the price goes up.  (iv) d = 0.756 , where d is one plus the rate of capital loss on the stock if the price goes down. (v) The continuously compounded annual expected return on the stock is 10%. What is the true probability of the stock price going up.
COT:  unding to two decimal places was not asked for, and there is a 0.52 option, so the answer must be I.
TrueAnswer:  I
Extracted Answer:  None
----------------------------------------
Question:  Mr. I.F.Sarbopurchased a fire insurance policy for his home withan annual premium of $32 on July 17. On September 22 hecanceled his policy. What was his refund?
COT:   $32 = $26.56, so $32 - ($32/365) * 62 = $32 - $5.44 = $26.56, then ($32/365) * 62 = $5.44, then $32
TrueAnswer:  F
Extracted Answer:  None
----------------------------------------
Question:  Mr. I.F.Sarbopurchased a fire insurance policy for his home withan annual premium of $32 on July 17. On September 22 hecanceled his policy. What was his refund?
COT:  32 * 298/365 ≈ $26.06
   Refund ≈ $32 * 0.8144 ≈ $26.06
   Refund ≈ $32 * 298/365 ≈ $26.06
   Refund
TrueAnswer:  F
Extracted Answer:  None
----------------------------------------
Question:  Mr. I.F.Sarbopurchased a fire insurance policy for his home withan annual premium of $32 on July 17. On September 22 hecanceled his policy. What was his refund?
COT:  on, we get:
$32 * (365 - 255)/365 = $32 * 110/365 = $9.59 is not an option.

However, if we multiply
TrueAnswer:  F
Extracted Answer:  None
----------------------------------------
Question:  Mr. I.F.Sarbopurchased a fire insurance policy for his home withan annual premium of $32 on July 17. On September 22 hecanceled his policy. What was his refund?
COT:  ys.
81. The policy was not in effect for 298 days.
82. We will calculate the portion of the year the
TrueAnswer:  F
Extracted Answer:  None
----------------------------------------
Question:  Mr. I.F.Sarbopurchased a fire insurance policy for his home withan annual premium of $32 on July 17. On September 22 hecanceled his policy. What was his refund?
COT:  efund = $32 * (1 - (67 / 365))
   Refund = $32 * (1 - 0.1836)
   Refund = $32 * 0.8164
   Refund = $
TrueAnswer:  F
Extracted Answer:  still not available. Let's try another method.

   Refund = Annual premium * (1 - (Days used / Total days in a year))
   Refund = $32 * (1 - (67 / 365))
   Refund = $32 * (1 - 0.1836)
   Refund = $32 * 0.8164
   Refund = $
----------------------------------------
Question:  Record the maturity date for a draft dated (a) November 12 and payable 60 days after date, (b) June 10 and payable 3 months after date, (c) March 3 and payable 30 days after sight if it is accepted March 15, and (d) October 4 and payable 6 months after sight if it is acceptedOctober 25.
COT:  uary 10, September 10, April 14, April 25.

The answer is J is not correct, but the closest one is A
TrueAnswer:  J
Extracted Answer:  J is not correct, but the closest one is A
----------------------------------------
Question:  Two cousins took title to real estate as joint tenants with the right of survivorship. The first cousin put up his interest in the joint tenancy as security for a $20,000 loan and signed a judgment note. It was later entered as a judgment against the first cousin's interest in the real estate. The first cousin died a year later. The second cousin decided to sell the property, but the mortgagee filed an action to prevent the sale and to enforce his interest in the property. The second cousin defended on the basis that any lien on the first cousin's interest in the property was extinguished on the first cousin's death. Will the court enforce the lien of the mortgagee against the sale of the property by the surviving second cousin?
COT:   because the second cousin's knowledge of the first cousin's debt is not relevant.

The answer is B.
TrueAnswer:  D
Extracted Answer:  B
----------------------------------------

Above: even though some of the incorrect answers are actually correct (but just don't end in "The answer is A." format), there are too many diverse formats to account for, so just dropped them all.

##### keep only rows with correct extracted answers

In [8]:
df = df[df['extracted_answer'] == df['answer']].reset_index(drop=True)
print(df.shape)
print(df.question.nunique())

(130112, 10)
10503

In [9]:
df.head()

,question_id,question,options,answer,answer_index,category,src,cot_id,cot_content,extracted_answer
0,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,0,1. Advertising regulatory bodies typically aim...,I
1,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,1,"First, typical advertising regulatory bodies a...",I
2,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,2,1. Advertising regulatory bodies typically aim...,I
3,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,3,Typical advertising regulatory bodies aim to e...,I
4,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,business,ori_mmlu-business_ethics,4,"First, typical advertising regulatory bodies a...",I

## remove some samples from training data to use as test data

##### whether to sample using question_ids or question -- use question because it turns out some questions have multiple question_id's

In [10]:
print('# unique question_ids:', df['question_id'].nunique())
print('# unique questions:', df['question'].nunique())

# unique question_ids: 10688
# unique questions: 10503

In [11]:
unique_pairs = df[['question', 'question_id']].drop_duplicates()
print(unique_pairs.shape)

(10688, 2)

In [12]:
#question_id's that map to multiple questions
question_ids_multiple_questions = (
    df.groupby('question_id')['question']
      .nunique()
      .reset_index(name='num_questions')
      .query('num_questions > 1')
)

question_ids_multiple_questions

Empty DataFrame
Columns: [question_id, num_questions]
Index: []

In [13]:
#question that has multiple question_id values
questions_multiple_ids = (
    df.groupby('question')['question_id']
      .nunique()
      .loc[lambda x: x > 1]
      .sort_values(ascending=False)
)

questions_multiple_ids

question
Which of the following is true?                                                                                                                                                                                                                                                                     5
A biologist deals with things on a microscopic level. To A biologist deals with things on a microscopic level. To describe cellular dimensions and the amount of materials present at the cellular level, units of an appropriately small size are needed. What are these units of measurements?    3
What is the difference between a kinesis and a taxis?                                                                                                                                                                                                                                               3
IfDNAaseis added to a bacterial cell, the DNA is hydrolyzed , the cell cannot make any more proteins and eventually dies. IfDNAaseis added to RNA viruses, they continue to produce new proteins. Explain.                                                                                          3
Which of the following statements is correct?\n                                                                                                                                                                                                                                                     3
                                                                                                                                                                                                                                                                                                   ..
Which statement is closest to characterizing the principal difference between the positions adopted by Hobbes and Locke?                                                                                                                                                                            2
Why are the elements carbon, hydrogen, oxygen, and nitrogen (C, H, O, N) of immense importance in living matter ?                                                                                                                                                                                   2
Which statement is true?                                                                                                                                                                                                                                                                            2
Why would one call a flock of birds a \textquotedblleftsociety\textquotedblright?                                                                                                                                                                                                                   2
Why would you not expect conjugation among a group of paramecia that had descended from a single individual through repeated fission?                                                                                                                                                               2
Name: question_id, Length: 156, dtype: int64

##### remove subset from training set

In [14]:
#get list of unique questions in training set
unique_questions = df['question'].unique()

#randomly select 500 questions -- these questions will be removed from training set, and added to test set
rng = np.random.default_rng(42)
n_samples_move_from_train_to_test = 500
selected_questions = rng.choice(unique_questions, size=n_samples_move_from_train_to_test, replace=False) 

#create df for selected questions to use in test set later
df_test_additional = df[df['question'].isin(selected_questions)].reset_index(drop=True)

#remove selected questions from training set
train_df_with_subset_removed = df[~df['question'].isin(selected_questions)].reset_index(drop=True)

##### finalize training data

In [15]:
#check numbers
print(train_df_with_subset_removed.shape)
print(train_df_with_subset_removed.question.nunique())
print('check numbers:', df['question'].nunique() - n_samples_move_from_train_to_test == train_df_with_subset_removed.question.nunique())

(123920, 10)
10003
check numbers: True

###### write question in SFT format (sft_input column)

In [16]:
#questions have different numbers of choices
train_df_with_subset_removed['n_choices'] = train_df_with_subset_removed.apply(lambda row: len(row['options']), axis=1).tolist()
print(set(train_df_with_subset_removed['n_choices']))
# train_df_with_subset_removed[train_df_with_subset_removed['n_choices'] == 3].head()#['options']

{3, 4, 5, 6, 7, 8, 9, 10}

In [17]:
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']


def write_sft_input(row):
    #write string for options
    options = row['options']
    
    options_string = ""
    for i, option in enumerate(options):
        options_string += f"\n{letters[i]}. {option}"

    #write sft input
    question = row['question']
    sft_input = f'{question}{options_string}'

    return sft_input

In [18]:
#format input and output for all rows
train_df_with_subset_removed['sft_input'] = train_df_with_subset_removed.apply(write_sft_input, axis=1)
#sft_output is train_df_with_subset_removed['cot_content']

###### check lengths of examples

In [19]:
#check lengths: sft_input + sft_output < 2048*3
train_df_with_subset_removed['total_length'] = train_df_with_subset_removed['sft_input'].str.len() + train_df_with_subset_removed['cot_content'].str.len()
train_df_with_subset_removed['total_length'].describe()
print(train_df_with_subset_removed['total_length'].describe())

#keep only rows where total_length < 2048*3
max_length = 2048*3
train_df_final = train_df_with_subset_removed[train_df_with_subset_removed['total_length'] < max_length].reset_index(drop=True)
print(train_df_final['total_length'].describe())

count    123920.000000
mean       1859.001541
std         878.859056
min         192.000000
25%        1197.000000
50%        1732.000000
75%        2385.000000
max        8737.000000
Name: total_length, dtype: float64
count    123836.000000
mean       1855.643157
std         869.508099
min         192.000000
25%        1197.000000
50%        1732.000000
75%        2384.000000
max        6134.000000
Name: total_length, dtype: float64

##### save training data to json

In [20]:
#lood at example
idx = 11
print('sft_input:')
print(train_df_final.iloc[idx]['sft_input'])

print('\nsft_output:')
print(train_df_final.iloc[idx]['cot_content'])

sft_input:
Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.
A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practices, Wants, Fear, Trivial
I. Unsafe practices, Distress, Fear, Serious

sft_output:
First, we need to consider the typical guidelines for advertising regulatory bodies. They usually aim to ensure that advertisements do not have a negative impact on the public.

The first part of the statement is "encourage _______ practices". Since the goal is to prevent harm, it's reasonable to assume that regulatory bodies would want to discourage "unsafe" practices rather than "safe" ones.

Next, we consider "cause unnecessary ________". In this context, "distress" seems more fitting than "wants", "joy", or "fear", as it aligns with the goal of preventing harm.

Then, we have "_____". Given the context, "fear" seems like a suitable option, as it can be a negative emotion that regulatory bodies might want to avoid.

Finally, we consider "must not cause _______ offence". The word "serious" seems more fitting than "trivial", as regulatory bodies would likely be more concerned with preventing serious offense rather than trivial ones.

Considering all these points, the correct answer should be the option that combines "unsafe practices", "distress", "fear", and "serious".

The answer is I.

In [21]:
### create json file

#format data for sft
data = []

for idx in tqdm(range(train_df_final.shape[0])):
    row = train_df_final.iloc[idx]
    item = {
        "instruction": row["sft_input"],
        "input": "",
        "output": row["cot_content"]
    }
    data.append(item)

#save to JSON file
with open("data/mmluprocot.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("Final # of samples in json file:", len(data))
print("Complete!")

  0%|                                                              | 0/123836 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████| 123836/123836 [00:03<00:00, 31524.92it/s]

Final # of samples in json file: 123836
Complete!

## create test dataset: combine test_df + samples removed from training set

In [22]:
#combine test_df + samples removed from training set
test_df_final = pd.concat([test_df, df_test_additional], ignore_index=True)

#keep only unique questions
test_df_final = test_df_final.drop_duplicates(subset='question')

In [23]:
#check
print('# unique questions in test set:', test_df_final.question.nunique())
print('check:', test_df.question.nunique() + n_samples_move_from_train_to_test == test_df_final.question.nunique())

# unique questions in test set: 567
check: True

In [24]:
#check that there is no train / test overlap
qs_unique_train = set(train_df_final['question'])
qs_unique_test = set(test_df_final['question'])

overlap = qs_unique_train.intersection(qs_unique_test)
print(len(overlap))
print(overlap)

0
set()

In [25]:
#format sft_input for all rows
test_df_final['sft_input'] = test_df_final.apply(write_sft_input, axis=1)

In [26]:
test_df_final.head()

,question_id,question,options,answer,answer_index,category,src,cot_id,cot_content,extracted_answer,sft_input
0,0,The symmetric group $S_n$ has $\n\factorial{n}...,"[0, 30, 3, 10, 12, 50, 2, 100, 20, 5]",A,0,math,cot_lib-abstract_algebra,0,"We are given a problem with two parts, but the...",NaN,The symmetric group $S_n$ has $\n\factorial{n}...
9,1,Let V be the set of all real polynomials p(x)....,[ST + TS is the identity map of V onto itself....,H,7,math,cot_lib-college_mathematics,0,Given transformations T and S defined on V by:...,NaN,Let V be the set of all real polynomials p(x)....
25,2,Let A be the set of all ordered pairs of integ...,"[-5, 0, -3, -7, -4, -6, -1, -2, -9]",E,4,math,cot_lib-college_mathematics,0,We are given the equation 7m + 12n = 22. We ne...,NaN,Let A be the set of all ordered pairs of integ...
29,3,A tank initially contains a salt solution of 3...,"[3 + e^-2, 2 - e^-4, 2 - e^-2, 3 + e^-4, 2 + e...",I,8,math,cot_lib-college_mathematics,0,"Initially, there are 3 grams of salt in the ta...",NaN,A tank initially contains a salt solution of 3...
31,4,A total of 30 players will play basketball at ...,"[Multiply 5 by 5 to find 25 teams., Divide 30 ...",B,1,math,cot_lib-elementary_mathematics,0,1. We know there are 30 players in total.\n2. ...,NaN,A total of 30 players will play basketball at ...

In [27]:
#create new question_id's
test_df_final['question_id_new'] = list(range(1, test_df_final.shape[0]+1))
test_df_final['question_id_new'] = test_df_final['question_id_new'].astype(str) + '-' + test_df_final['src']

In [28]:
### MOVE DATA BY HAND INTO CORRECT FOLDER : learn-better/evolm/evaluation/cot-eval-harness/data/cooked

### create jsonl file

data = []

# Write JSONL file
with open("data/mmluprocot.jsonl", "w", encoding="utf-8") as f:
    for idx in tqdm(range(test_df_final.shape[0])):
        row = test_df_final.iloc[idx]
        item = {
            "id": str(row["question_id_new"]),
            "problem": str(row["sft_input"]),
            "gt_solution": str(row["answer"]),
            "gt_answer": str(row["answer"])
        }
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print("Final # of samples in json file:", len(data))
print("Complete!")

100%|████████████████████████████████████████████████████| 567/567 [00:00<00:00, 19077.41it/s]

Final # of samples in json file: 0
Complete!